default_platform(:ios)

platform :ios do
  # Configuración común
  SCHEME = "Proyecto1"              # Cambia por tu esquema
  PROJECT = "../Proyecto1.xcodeproj"
  CONFIGURATION = "Debug"
  OUTPUT_DIR = "build"              # Carpeta de artefactos
  EXPORT_METHOD = "ad-hoc"          # "app-store", "ad-hoc", "development", "enterprise"

  desc "Solo compila el proyecto (sin IPA)"
  lane :build do
    sh(
      "bash",
      "-lc",
      [
        "set -o pipefail",
        "xcodebuild",
        "-project #{PROJECT}",
        "-scheme #{SCHEME}",
        "-configuration #{CONFIGURATION}",
        "-destination 'generic/platform=iOS Simulator'",
        "CODE_SIGNING_ALLOWED=NO",
        "SWIFT_VERSION=5.0",
        "clean",
        "build | xcbeautify"
      ].join(" ")
    )
  end

  desc "Genera IPA firmado y listo para distribuir"
  lane :build_ipa do
    # Opcional: incrementar build number automáticamente
    # increment_build_number(xcodeproj: "Proyecto1.xcodeproj")

    # Genera el .ipa (y .xcarchive)
    gym(
      project: PROJECT,
      scheme: SCHEME,
      configuration: CONFIGURATION,
      clean: true,
      export_method: EXPORT_METHOD,   # Ajusta según tu necesidad
      output_directory: OUTPUT_DIR,
      output_name: "Proyecto1.ipa",
      include_bitcode: false,         # App Store ya no requiere bitcode
      include_symbols: true,
      silent: false
    )

    # Si quieres, sube a TestFlight automáticamente:
    # pilot(upload: true, ipa: File.join(OUTPUT_DIR, "Proyecto1.ipa"))
  end
end
