name: PR Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.3.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build project
        run: |
          bundle exec fastlane ios build
